# Generated by Django 4.1.6 on 2023-07-11 23:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Esportes',
            },
        ),
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=300, verbose_name='Rua')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=250, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('lat', models.CharField(max_length=30, verbose_name='Latitude')),
                ('lon', models.CharField(max_length=30, verbose_name='Longitude')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controles.esporte')),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date(2023, 7, 11), verbose_name='Data')),
                ('hora', models.TimeField(max_length=10, verbose_name='Hora')),
                ('duração', models.CharField(max_length=10, verbose_name='Duração')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controles.local')),
            ],
            options={
                'verbose_name_plural': 'Agendamentos',
            },
        ),
    ]
