# Generated by Django 4.2.3 on 2023-07-11 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 23, 32, 12, 789608, tzinfo=datetime.timezone.utc), verbose_name='Data'),
        ),
        migrations.RemoveField(
            model_name='local',
            name='tipo',
        ),
        migrations.AddField(
            model_name='local',
            name='tipo',
            field=models.ManyToManyField(to='controles.esporte', verbose_name='Tipo'),
        ),
    ]
