# Generated by Django 4.2.3 on 2023-07-11 23:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0002_alter_agendamento_data_remove_local_tipo_local_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 11, 23, 35, 44, 496658, tzinfo=datetime.timezone.utc), null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='duração',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='hora',
            field=models.TimeField(blank=True, max_length=10, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controles.local'),
        ),
        migrations.AlterField(
            model_name='esporte',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='local',
            name='bairro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='local',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='local',
            name='cidade',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='local',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='local',
            name='lat',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='local',
            name='lon',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='local',
            name='numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='local',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='local',
            name='rua',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.ManyToManyField(blank=True, null=True, to='controles.esporte', verbose_name='Tipo'),
        ),
    ]
