# Generated by Django 4.2.3 on 2023-07-16 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0003_alter_agendamento_data_alter_agendamento_duração_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esporte',
            name='cor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='esporte',
            name='icon_url',
            field=models.ImageField(default='media/leaflet/images/marker-icon.png', upload_to='media/leaflet/images/', verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 16, 22, 39, 46, 825617, tzinfo=datetime.timezone.utc), null=True, verbose_name='Data'),
        ),
    ]
