# Generated by Django 4.2.3 on 2023-08-09 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0005_rename_duração_agendamento_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 8, 9, 23, 50, 0, 245178, tzinfo=datetime.timezone.utc), null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='esporte',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Futebol', 'Futebol'), ('Futebol G. Sintetica', 'Futebol G. Sintetica'), ('Futebol Campo', 'Futebol Campo'), ('Volei Quadra', 'Voleu Quadra')], max_length=30, verbose_name='Tipo'),
        ),
    ]
