# Generated by Django 4.2.3 on 2023-08-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0006_alter_agendamento_data_alter_esporte_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
