# Generated by Django 4.2.3 on 2023-08-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controles', '0007_alter_agendamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='tipo',
            field=models.ManyToManyField(blank=True, to='controles.esporte', verbose_name='Tipo'),
        ),
    ]
